# This module defines the schema for the `BusinessModelCanvas` entity and its associations in an ArangoDB database.
# It represents the structure and relationships of a business model canvas in the application.
defmodule Vectora.Tools.BusinessModelCanvas do

  # Includes functionality from the ArangoXEcto.Schema module,
  # which provides macros and functions to define ArangoDB collections and their associations.
  use ArangoXEcto.Schema

  # Imports functions from the Ecto.Changeset module to help with data validation and changeset creation.
  import Ecto.Changeset

  # Defines the `business_model_canvas` collection schema.
  schema "business_model_canvas" do
    # Defines fields for the schema.
    field :name, :string
    field :description, :string

    # Defines outgoing edges (relationships) from the `business_model_canvas` collection to other collections.
    # `racis` connects to the RACI collection.
    # `partners` connects to the Partner collection.
    # `products` connects to the Product collection.
    # `value_propositions` connects to the ValueProposition collection.
    outgoing :racis, Vectora.Tools.RACI
    outgoing :partners, Vectora.Tools.Partner
    outgoing :products, Vectora.Tools.Product
    outgoing :value_propositions, Vectora.Tools.ValueProposition

    # Automatically generates fields for timestamps (inserted_at and updated_at).
    timestamps()
  end

  # @doc false hides this function from autogenerated documentation.
  # This function creates a changeset for the BusinessModelCanvas schema, which helps validate and track changes to records.
  #
  # @param business_model_canvas - The current state of the BusinessModelCanvas record.
  # @param attrs - The attributes with which we want to update the BusinessModelCanvas record.
  # @return - Returns a changeset that represents the changes to be made.
  def changeset(business_model_canvas, attrs) do
    business_model_canvas
    # Casts the provided attributes to their respective fields.
    |> cast(attrs, [:name, :description])
    # Validates that the required fields are present in the changeset.
    |> validate_required([:name, :description])
  end
end
